In [11]:
import panel as pn
pn.extension('plotly')
import plotly.express as px
import pandas as pd
import hvplot.pandas
import matplotlib.pyplot as plt
import numpy as np
import os 
from pathlib import Path
from dotenv import load_dotenv
import datetime as dt
%matplotlib inline

import warnings
warnings.filterwarnings('ignore')

In [12]:
inputf = Path("/Users/jeremyseidman/cryptracker/dummy file.csv")
dataframe = pd.read_csv(inputf)

In [13]:
dataframe

,trackable and unlocked,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,eco system,Currency,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Jeremy,Dad,Josh,Jesse,Jeremy + Dad # coins/ tokens,All other # coins/ tokens,NaN
2,SOL,SOL,1.1,0,0,0,NaN,NaN
3,BTC,BTC,1.2,1,0,0,2.2,NaN
4,XTZ,XTZ,1.3,2,1,1,NaN,5.3
5,SOL,RAY,1.4,0,0,0,NaN,NaN
6,DOT,DOT,1.5,3,0,0,4.5,NaN
7,SOL,SRM,1.6,0,0,0,NaN,NaN
8,ATOM,ATOM,1.7,4.1,0,0,5.8,NaN
9,ETH,USDC,1.8,0,0,0,NaN,NaN
10,SOL,FTT,1.9,0,0,0,NaN,NaN
11,ETH,ETH,2,5.33,0,0,7.33,NaN
12,SOL,ORCA,2.1,0,0,0,NaN,NaN
13,SOL,TULIP,2.2,0,0,0,NaN,NaN
14,ETH,LINK,2.3,0,0,0,NaN,NaN
15,ETH,SUSHI,2.4,0,0,0,NaN,NaN
16,ADA,ADA,2.5,6,0,0,8.504,NaN
17,ETH,UNI,2.6,7.7,0,0,10.3,NaN
18,MATIC,MATIC,2.7,0,0,0,NaN,NaN
19,ETH,GRT,2.8,0,0,0,NaN,NaN
20,SOL,MER,2.9,0,0,0,NaN,NaN
21,SOL,PORT,3,0,0,0,NaN,NaN
22,FTM,FTM,3.1,0,0,0,NaN,NaN
23,VET,VET,3.2,8,0,0,11.2,NaN
24,SOL,SNY,3.3,0,0,0,NaN,NaN
25,SOL,MNGO,3.4,0,0,0,NaN,NaN
26,SOL,SBR,3.5,0,0,0,NaN,NaN
27,BSC,BDL,3.6,0,0,0,NaN,NaN
28,SOL,LIQ,3.7,0,0,0,NaN,NaN
29,ETH,REN,3.8,0,0,0,NaN,NaN
...,...,...,...,...,...,...,...,...
350,1.6,SOL,xxx,NaN,NaN,NaN,NaN,NaN
351,1.7,SOL,xxx,NaN,NaN,NaN,NaN,NaN
352,1.8,SOL,xxx,NaN,NaN,NaN,NaN,NaN
353,1.9,SOL,xxx,NaN,NaN,NaN,NaN,NaN
354,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
355,SOL locations,NaN,NaN,NaN,NaN,NaN,NaN,NaN
356,amount,chain,address,NaN,NaN,NaN,NaN,NaN
357,1.1,SOL,xxx,NaN,NaN,NaN,NaN,NaN
358,1.2,SOL,xxx,NaN,NaN,NaN,NaN,NaN
359,1.3,SOL,xxx,NaN,NaN,NaN,NaN,NaN
360,1.4,SOL,xxx,NaN,NaN,NaN,NaN,NaN
361,1.5,SOL,xxx,NaN,NaN,NaN,NaN,NaN
362,1.6,SOL,xxx,NaN,NaN,NaN,NaN,NaN
363,1.7,SOL,xxx,NaN,NaN,NaN,NaN,NaN
364,1.8,SOL,xxx,NaN,NaN,NaN,NaN,NaN
365,1.9,SOL,xxx,NaN,NaN,NaN,NaN,NaN
366,0,SOL,xxx,NaN,NaN,NaN,NaN,NaN
367,0,SOL,xxx,NaN,NaN,NaN,NaN,NaN
368,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
369,Crypto I've lost,NaN,NaN,NaN,NaN,NaN,NaN,NaN
370,When,Ticker,Amount,How I lost it,NaN,NaN,NaN,NaN
371,xxx,ETH,1,xxx,NaN,NaN,NaN,NaN
372,1/1/00,BTC,2,xxx,NaN,NaN,NaN,NaN
373,1/1/00,SOL,3,xxx,NaN,NaN,NaN,NaN
374,1/1/00,ETH,4.55,xxx,NaN,NaN,NaN,NaN
375,xxx,SEM,6,xxx,NaN,NaN,NaN,NaN
376,xxx,FA,7,xxx,NaN,NaN,NaN,NaN
377,xxx,ETI,8,xxx,NaN,NaN,NaN,NaN
378,xxx,BTRL,9,xxx,NaN,NaN,NaN,NaN
379,xxx,HNS,1010,xxx,NaN,NaN,NaN,NaN

In [10]:
for i in rows:
    if dataframe[dataframe.columns[1]].isnull()==True:
        dataframe&i =

0      False
1      False
2      False
3      False
4      False
5      False
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20     False
21     False
22     False
23     False
24     False
25     False
26     False
27     False
28     False
29     False
       ...
350    False
351    False
352    False
353    False
354     True
355     True
356    False
357    False
358    False
359    False
360    False
361    False
362    False
363    False
364    False
365    False
366    False
367    False
368     True
369     True
370    False
371    False
372    False
373    False
374    False
375    False
376    False
377    False
378    False
379    False
Name: Unnamed: 1, Length: 380, dtype: bool